### PR TITLE
Fixed compatibility with composer 2.1

### LINKED ISSUE #37: Issues with composer 2.1
Hello,

I tested foxy with the new composer version 2.1 with the following result:

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Installer\InstallationManager, instance of Composer\Repository\RepositoryManager given, called in /home/dev/some_dir/acme/project/vendor/foxy/foxy/Util/LockerUtil.php on line 41 and defined in phar:///usr/local/bin/composer/src/Composer/Package/Locker.php:60
Stack trace:
#0 /home/dev/some_dir/acme/project/vendor/foxy/foxy/Util/LockerUtil.php(41): Composer\Package\Locker->__construct()
#1 /home/dev/some_dir/acme/project/vendor/foxy/foxy/Fallback/ComposerFallback.php(101): Foxy\Util\LockerUtil::getLocker()
#2 /home/dev/some_dir/acme/project/vendor/foxy/foxy/Foxy.php(179): Foxy\Fallback\ComposerFallback->save()
#3 [internal function]: Foxy\Foxy->init()
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(190): call_user_func()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.p in phar:///usr/local/bin/composer/src/Composer/Package/Locker.php on line 60

Fatal error: Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Installer\InstallationManager, instance of Composer\Repository\RepositoryManager given, called in /home/dev/some_dir/acme/project/vendor/foxy/foxy/Util/LockerUtil.php on line 41 and defined in phar:///usr/local/bin/composer/src/Composer/Package/Locker.php:60
Stack trace:
#0 /home/dev/some_dir/acme/project/vendor/foxy/foxy/Util/LockerUtil.php(41): Composer\Package\Locker->__construct()
#1 /home/dev/some_dir/acme/project/vendor/foxy/foxy/Fallback/ComposerFallback.php(101): Foxy\Util\LockerUtil::getLocker()
#2 /home/dev/some_dir/acme/project/vendor/foxy/foxy/Foxy.php(179): Foxy\Fallback\ComposerFallback->save()
#3 [internal function]: Foxy\Foxy->init()
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(190): call_user_func()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.p in phar:///usr/local/bin/composer/src/Composer/Package/Locker.php on line 60
```

It seems foxy is not yet compatible with 2.1, or do I need to configure something?

Thanks!

Bye Defcon0

### PR DESCRIPTION
**Pull request by SamMousa**
Fixes #37

### CODE REVIEW

**Comment by dsturm** [comment]
Hej @SamMousa,

shouldn't we check, whether `Composer::RUNTIME_API_VERSION` is at least `2.0.0` and therefor use

```php
version_compare(Composer::RUNTIME_API_VERSION, '2.0.0', '>=')
```

Or is there a reason to explicitly check for `2.0.0` and `2.1.0`?

**Comment by francoispluchino** [comment]
@SamMousa It is preferable to use `version_compare` function.

**Comment by SamMousa** [comment]
I used strict comparison because that's what was done in original code. I'm fine updating it to use version compare

**Comment by SamMousa** [comment]
@francoispluchino, the PR is done but CI is broken.

**Comment by SamMousa** [comment]
Bump

**Comment by francoispluchino** [comment]
Thank you!

**Pull request merged**
